### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by manni8436** [Barry-Greaves/world-emoji-day#6]

**Comment by Barry-Greaves** [comment]
Desktop Wireframe and design attached. 

Import links for fonts :

<style>
  @import url("https://use.typekit.net/ijo7yff.css");
</style>

<style>
  @import url("https://use.typekit.net/ijo7yff.css");
</style>

![emoji match](https://user-images.githubusercontent.com/107034179/179129129-8a8eee13-83e3-42e1-a7d2-db20b957b4a8.png)

**Comment by Barry-Greaves** [comment]
![desktop-wireframe](https://user-images.githubusercontent.com/107034179/179365726-cff4df16-2770-4e09-8030-779290b917b0.png)
![LEADERBOARD-DESKTOP](https://user-images.githubusercontent.com/107034179/179365728-74cd2ed8-a1da-4f09-90a6-bf20cf40e767.png)
![mobile-wireframe](https://user-images.githubusercontent.com/107034179/179365730-6a154386-3803-4284-bb74-d1c3406e2284.png)
![tablet-wireframe](https://user-images.githubusercontent.com/107034179/179365736-dc9c9b25-1735-4327-8365-d71e9b105e72.png)
